// Every command the frontend may call has to appear here, so tauri-build
// generates an "allow-" permission for it, and again in capabilities/main.json,
// so that permission is actually granted to the window. Missing either one
// compiles cleanly and fails only when the user clicks the button. The tests in
// src/main.rs compare this list, the generate_handler! list, and the capability
// file, and fail if they ever drift apart.
fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "get_ai_settings",
            "save_ai_settings",
            "forget_ai_key",
            "ai_payload_preview",
            "ai_coaching_summary",
            "get_insight_feed",
            "get_spending_patterns",
            "explain_insight",
            "get_net_worth_trend",
            "save_net_worth_entry",
            "delete_net_worth_entry",
            "pick_export_file",
            "export_transactions",
            "delete_transaction",
            "ai_ask",
            "test_ai_connection",
            "get_home_summary",
            "list_accounts",
            "create_account",
            "set_account_spending_availability",
            "preview_import",
            "apply_csv_mapping",
            "confirm_import",
            "reset_csv_profile",
            "list_transactions",
            "correct_transaction",
            "undo_last_category_change",
            "get_review_summary",
            "get_shared_settings",
            "save_shared_settings",
            "set_shared_rule",
            "get_category_settings",
            "update_category_rule",
            "delete_category_rule",
            "set_recurring_preference",
            "set_income_source_preference",
            "add_manual_transaction",
            "get_plan_summary",
            "preview_plan",
            "save_plan",
            "get_goals_summary",
            "create_goal",
            "update_goal",
            "contribute_goal",
            "get_insights_summary",
            "save_quick_net_worth",
            "add_account_balance",
            "get_planning_balances",
            "get_home_dashboard",
            "get_backup_status",
            "create_backup",
            "restore_backup",
            "get_data_safety_status",
            "preview_legacy_repair",
            "repair_legacy_data",
            "reset_financial_data",
            "pick_import_files",
            "pick_backup_file",
        ]),
    ))
    .expect("failed to run tauri-build");
}
