import { useCallback, useEffect, useState } from "react";
import { addManualTransaction, loadTransactions } from "./api";
import type { Account } from "./types";

interface Props { onDataChanged:()=>void }
const blank=()=>({account:"",date:new Date().toISOString().slice(0,10),description:"",merchant:"",amount:"",direction:"debit",category:"Uncategorized",note:""});
function ManualTransactionForm({onDataChanged}:Props){const[accounts,setAccounts]=useState<Account[]>([]);const[categories,setCategories]=useState<string[]>([]);const[form,setForm]=useState(blank);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState("");const load=useCallback(async()=>{try{const p=await loadTransactions({accountRef:null,search:"",category:"",direction:"",startDate:"",endDate:"",sort:"date",descending:true,offset:0,limit:1});setAccounts(p.accounts);setCategories(p.categories);}catch(c){setError(c instanceof Error?c.message:String(c));}},[]);useEffect(()=>{void load();},[load]);// An identical row is refused by default because a double-click is more
// likely than the same purchase twice. Only the user knows which it was, so
// the refusal comes with a way to say "it really happened twice".
const[duplicate,setDuplicate]=useState(false);const save=async(allowDuplicate=false)=>{setBusy(true);setError("");setDone("");try{await addManualTransaction({accountId:Number(form.account),date:form.date,description:form.description,merchant:form.merchant,amount:Number(form.amount),direction:form.direction,category:form.category,note:form.note,allowDuplicate});setDone("Transaction saved.");setDuplicate(false);setForm({...blank(),account:form.account});onDataChanged();}catch(c){const message=c instanceof Error?c.message:String(c);setDuplicate(message.includes("Add it anyway"));setError(message);}finally{setBusy(false);}};return <div className="form-card"><div className="panel-head"><div><strong>Add one transaction manually</strong><p>Useful for cash purchases, corrections, or activity without a statement export.</p></div></div>{error&&<div className="inline-error">{error}{duplicate&&<div className="button-row"><button type="button" className="ghost-button" disabled={busy} onClick={()=>void save(true)}>Add it anyway</button></div>}</div>}{done&&<p className="success-text">{done}</p>}<div className="form-grid"><label>Account<select value={form.account} onChange={e=>setForm({...form,account:e.target.value})}><option value="">Choose account…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Amount ($)<input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>Direction<select value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}><option value="debit">Money out</option><option value="credit">Money in</option></select></label><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Merchant (optional)<input value={form.merchant} onChange={e=>setForm({...form,merchant:e.target.value})}/></label><label>Note (optional)<input value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label></div><div className="button-row"><button disabled={busy||!form.account||!form.description||Number(form.amount)<=0} onClick={()=>void save(false)}>{busy?"Saving…":"Save transaction"}</button></div></div>}
export default ManualTransactionForm;
